package com.zyascend.NoBoring.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BUDEJIE_VIDEO".
*/
public class BudejieVideoDao extends AbstractDao<BudejieVideo, Long> {

    public static final String TABLENAME = "BUDEJIE_VIDEO";

    /**
     * Properties of entity BudejieVideo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property ShareUrl = new Property(1, String.class, "shareUrl", false, "SHARE_URL");
        public final static Property ThumbUrl = new Property(2, String.class, "thumbUrl", false, "THUMB_URL");
        public final static Property Title = new Property(3, String.class, "title", false, "TITLE");
        public final static Property VideoUrl = new Property(4, String.class, "videoUrl", false, "VIDEO_URL");
        public final static Property Tag = new Property(5, int.class, "tag", false, "TAG");
        public final static Property Np = new Property(6, String.class, "np", false, "NP");
    }


    public BudejieVideoDao(DaoConfig config) {
        super(config);
    }
    
    public BudejieVideoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BUDEJIE_VIDEO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"SHARE_URL\" TEXT," + // 1: shareUrl
                "\"THUMB_URL\" TEXT," + // 2: thumbUrl
                "\"TITLE\" TEXT," + // 3: title
                "\"VIDEO_URL\" TEXT," + // 4: videoUrl
                "\"TAG\" INTEGER NOT NULL ," + // 5: tag
                "\"NP\" TEXT);"); // 6: np
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BUDEJIE_VIDEO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BudejieVideo entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String shareUrl = entity.getShareUrl();
        if (shareUrl != null) {
            stmt.bindString(2, shareUrl);
        }
 
        String thumbUrl = entity.getThumbUrl();
        if (thumbUrl != null) {
            stmt.bindString(3, thumbUrl);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(4, title);
        }
 
        String videoUrl = entity.getVideoUrl();
        if (videoUrl != null) {
            stmt.bindString(5, videoUrl);
        }
        stmt.bindLong(6, entity.getTag());
 
        String np = entity.getNp();
        if (np != null) {
            stmt.bindString(7, np);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BudejieVideo entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String shareUrl = entity.getShareUrl();
        if (shareUrl != null) {
            stmt.bindString(2, shareUrl);
        }
 
        String thumbUrl = entity.getThumbUrl();
        if (thumbUrl != null) {
            stmt.bindString(3, thumbUrl);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(4, title);
        }
 
        String videoUrl = entity.getVideoUrl();
        if (videoUrl != null) {
            stmt.bindString(5, videoUrl);
        }
        stmt.bindLong(6, entity.getTag());
 
        String np = entity.getNp();
        if (np != null) {
            stmt.bindString(7, np);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public BudejieVideo readEntity(Cursor cursor, int offset) {
        BudejieVideo entity = new BudejieVideo( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // shareUrl
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // thumbUrl
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // title
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // videoUrl
            cursor.getInt(offset + 5), // tag
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // np
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BudejieVideo entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setShareUrl(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setThumbUrl(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTitle(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setVideoUrl(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTag(cursor.getInt(offset + 5));
        entity.setNp(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BudejieVideo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BudejieVideo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BudejieVideo entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
