package com.zyascend.NoBoring.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zyascend.NoBoring.dao.BudejieVideo;
import com.zyascend.NoBoring.dao.Fresh;
import com.zyascend.NoBoring.dao.Girl;
import com.zyascend.NoBoring.dao.TextJoke;
import com.zyascend.NoBoring.dao.TuWenJoke;
import com.zyascend.NoBoring.dao.WeiXin;

import com.zyascend.NoBoring.dao.BudejieVideoDao;
import com.zyascend.NoBoring.dao.FreshDao;
import com.zyascend.NoBoring.dao.GirlDao;
import com.zyascend.NoBoring.dao.TextJokeDao;
import com.zyascend.NoBoring.dao.TuWenJokeDao;
import com.zyascend.NoBoring.dao.WeiXinDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig budejieVideoDaoConfig;
    private final DaoConfig freshDaoConfig;
    private final DaoConfig girlDaoConfig;
    private final DaoConfig textJokeDaoConfig;
    private final DaoConfig tuWenJokeDaoConfig;
    private final DaoConfig weiXinDaoConfig;

    private final BudejieVideoDao budejieVideoDao;
    private final FreshDao freshDao;
    private final GirlDao girlDao;
    private final TextJokeDao textJokeDao;
    private final TuWenJokeDao tuWenJokeDao;
    private final WeiXinDao weiXinDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        budejieVideoDaoConfig = daoConfigMap.get(BudejieVideoDao.class).clone();
        budejieVideoDaoConfig.initIdentityScope(type);

        freshDaoConfig = daoConfigMap.get(FreshDao.class).clone();
        freshDaoConfig.initIdentityScope(type);

        girlDaoConfig = daoConfigMap.get(GirlDao.class).clone();
        girlDaoConfig.initIdentityScope(type);

        textJokeDaoConfig = daoConfigMap.get(TextJokeDao.class).clone();
        textJokeDaoConfig.initIdentityScope(type);

        tuWenJokeDaoConfig = daoConfigMap.get(TuWenJokeDao.class).clone();
        tuWenJokeDaoConfig.initIdentityScope(type);

        weiXinDaoConfig = daoConfigMap.get(WeiXinDao.class).clone();
        weiXinDaoConfig.initIdentityScope(type);

        budejieVideoDao = new BudejieVideoDao(budejieVideoDaoConfig, this);
        freshDao = new FreshDao(freshDaoConfig, this);
        girlDao = new GirlDao(girlDaoConfig, this);
        textJokeDao = new TextJokeDao(textJokeDaoConfig, this);
        tuWenJokeDao = new TuWenJokeDao(tuWenJokeDaoConfig, this);
        weiXinDao = new WeiXinDao(weiXinDaoConfig, this);

        registerDao(BudejieVideo.class, budejieVideoDao);
        registerDao(Fresh.class, freshDao);
        registerDao(Girl.class, girlDao);
        registerDao(TextJoke.class, textJokeDao);
        registerDao(TuWenJoke.class, tuWenJokeDao);
        registerDao(WeiXin.class, weiXinDao);
    }
    
    public void clear() {
        budejieVideoDaoConfig.clearIdentityScope();
        freshDaoConfig.clearIdentityScope();
        girlDaoConfig.clearIdentityScope();
        textJokeDaoConfig.clearIdentityScope();
        tuWenJokeDaoConfig.clearIdentityScope();
        weiXinDaoConfig.clearIdentityScope();
    }

    public BudejieVideoDao getBudejieVideoDao() {
        return budejieVideoDao;
    }

    public FreshDao getFreshDao() {
        return freshDao;
    }

    public GirlDao getGirlDao() {
        return girlDao;
    }

    public TextJokeDao getTextJokeDao() {
        return textJokeDao;
    }

    public TuWenJokeDao getTuWenJokeDao() {
        return tuWenJokeDao;
    }

    public WeiXinDao getWeiXinDao() {
        return weiXinDao;
    }

}
