package com.zyascend.NoBoring.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TU_WEN_JOKE".
*/
public class TuWenJokeDao extends AbstractDao<TuWenJoke, Long> {

    public static final String TABLENAME = "TU_WEN_JOKE";

    /**
     * Properties of entity TuWenJoke.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property ThumbUrl = new Property(2, String.class, "thumbUrl", false, "THUMB_URL");
        public final static Property PicUrl = new Property(3, String.class, "picUrl", false, "PIC_URL");
        public final static Property PicHeight = new Property(4, int.class, "picHeight", false, "PIC_HEIGHT");
        public final static Property Time = new Property(5, String.class, "time", false, "TIME");
        public final static Property ShareUrl = new Property(6, String.class, "shareUrl", false, "SHARE_URL");
    }


    public TuWenJokeDao(DaoConfig config) {
        super(config);
    }
    
    public TuWenJokeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TU_WEN_JOKE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"TITLE\" TEXT," + // 1: title
                "\"THUMB_URL\" TEXT," + // 2: thumbUrl
                "\"PIC_URL\" TEXT," + // 3: picUrl
                "\"PIC_HEIGHT\" INTEGER NOT NULL ," + // 4: picHeight
                "\"TIME\" TEXT," + // 5: time
                "\"SHARE_URL\" TEXT);"); // 6: shareUrl
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TU_WEN_JOKE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TuWenJoke entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String thumbUrl = entity.getThumbUrl();
        if (thumbUrl != null) {
            stmt.bindString(3, thumbUrl);
        }
 
        String picUrl = entity.getPicUrl();
        if (picUrl != null) {
            stmt.bindString(4, picUrl);
        }
        stmt.bindLong(5, entity.getPicHeight());
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(6, time);
        }
 
        String shareUrl = entity.getShareUrl();
        if (shareUrl != null) {
            stmt.bindString(7, shareUrl);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TuWenJoke entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String thumbUrl = entity.getThumbUrl();
        if (thumbUrl != null) {
            stmt.bindString(3, thumbUrl);
        }
 
        String picUrl = entity.getPicUrl();
        if (picUrl != null) {
            stmt.bindString(4, picUrl);
        }
        stmt.bindLong(5, entity.getPicHeight());
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(6, time);
        }
 
        String shareUrl = entity.getShareUrl();
        if (shareUrl != null) {
            stmt.bindString(7, shareUrl);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public TuWenJoke readEntity(Cursor cursor, int offset) {
        TuWenJoke entity = new TuWenJoke( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // thumbUrl
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // picUrl
            cursor.getInt(offset + 4), // picHeight
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // time
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // shareUrl
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TuWenJoke entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setThumbUrl(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPicUrl(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPicHeight(cursor.getInt(offset + 4));
        entity.setTime(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setShareUrl(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TuWenJoke entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TuWenJoke entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TuWenJoke entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
